version: '3'
services:
  ssbd03_mysql_db:
    image: mysql
    container_name: ssbd03_mysql_db
    hostname: ssbd03_mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./database/db_structure.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/db_init.sql:/docker-entrypoint-initdb.d/2.sql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  ssbd03_app:
    container_name: ssbd03_app
    hostname: ssbd03_app
    depends_on:
      - ssbd03_mysql_db
    build: .
    ports:
      - "8080:8080"
      - "9990:9990"
    expose:
      - "8080"
